server:
  port: 8085

spring:
  datasource:
    url: jdbc:sqlite://C:\\sqlite\\db\\razorpay.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.SQLiteDialect
